---

- hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
  tasks:
  - name: Create a new spark master instance 
    os_server:
      state: "{{ instance_state }}"
      name: spark-master
      image: 2a9630d7-2328-4bbd-bbe7-e125c7008558
      key_name: "{{ key_name }}"
      timeout: 200
      flavor: 3
      network: "{{ network_internal_name }}"
      security_groups: spark,default
      floating_ip_pools: "{{ network_external_name }}"
      meta:
        hostname: spark-master
        ansible_host_groups: spark_master
    register: spark_master

  - name: Create a new spark slaves
    os_server:
      state: "{{ instance_state }}"
      name: "{{ item }}"
      image: 2a9630d7-2328-4bbd-bbe7-e125c7008558
      key_name: "{{ key_name }}"
      timeout: 200
      flavor: 3
      security_groups: spark,default
      floating_ip_pools: "{{ network_external_name }}"
      nics:
        - net-name: "{{ network_internal_name }}"
      meta:
        hostname: "{{ item }}"
        ansible_host_groups: spark_slaves
    register: spark_slaves
    with_sequence: 
      start=1
      end="{{ nbr_of_slaves }}"
      format=spark-slave%02x
